function(commit_adoption_fixture repo_path)
    run_expect_success(git -C "${repo_path}" init -b main)
    run_expect_success(git -C "${repo_path}" add --all)
    run_expect_success(git -C "${repo_path}" -c user.name=QivenFixture -c user.email=fixture@example.invalid commit -m baseline)
endfunction()

function(make_adoption_fixture repo_path repo_name)
    generate_repo("${DEVKIT_ROOT}" "${repo_path}" "${repo_name}")
    file(REMOVE_RECURSE "${repo_path}/.qiven")
endfunction()

function(run_adoption mode repo_path result_variable output_variable)
    execute_process(COMMAND "${CMAKE_COMMAND}"
        -DDEVKIT_ROOT=${DEVKIT_ROOT} -DMODE=${mode} -DREPOSITORY=${repo_path}
        -DREPOSITORY_NAME=adopt-fixture -DCMAKE_PROJECT_NAME=adopt-fixture
        -DCMAKE_TARGET_NAME=adopt-fixture -DCMAKE_ALIAS=qiven::example
        -DCPP_NAMESPACE=qiven::example -DTEST_OPTION_NAME=QIVEN_EXAMPLE_BUILD_TESTS
        -DVS_SOLUTION_NAME=adopt-fixture -P "${DEVKIT_ROOT}/cmake/QivenRepoAdopt.cmake"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    set(${result_variable} "${result}" PARENT_SCOPE)
    set(${output_variable} "${output}\n${error}" PARENT_SCOPE)
endfunction()

function(assert_adoption_rejected result output context)
    if(result EQUAL 0)
        fail("adoption unexpectedly succeeded: ${context}\n${output}")
    endif()
endfunction()

function(assert_fixture_clean repo_path context)
    execute_process(COMMAND git -C "${repo_path}" status --porcelain=v1 --untracked-files=all
        RESULT_VARIABLE result OUTPUT_VARIABLE status ERROR_VARIABLE error)
    if(NOT result EQUAL 0 OR NOT status STREQUAL "")
        fail("fixture changed unexpectedly: ${context}\n${status}\n${error}")
    endif()
endfunction()

include("${DEVKIT_ROOT}/templates/cpp-library/managed-files.cmake")

# Exact files: check is read-only, apply adds metadata, sync is idempotent, and re-adoption is rejected.
set(adopt_exact "${fixtures}/adopt-exact")
make_adoption_fixture("${adopt_exact}" adopt-fixture)
file(SHA256 "${adopt_exact}/.editorconfig" exact_before)
commit_adoption_fixture("${adopt_exact}")
run_adoption(check "${adopt_exact}" exact_check_result exact_check_output)
if(NOT exact_check_result EQUAL 0)
    fail("exact adoption check failed: ${exact_check_output}")
endif()
assert_contains("${adopt_exact}/README.md" "adopt-fixture")
assert_fixture_clean("${adopt_exact}" "exact check")
run_adoption(apply "${adopt_exact}" exact_apply_result exact_apply_output)
if(NOT exact_apply_result EQUAL 0)
    fail("exact adoption apply failed: ${exact_apply_output}")
endif()
assert_exists("${adopt_exact}/.qiven/repo.json")
assert_exists("${adopt_exact}/.qiven/generated-state.cmake")
file(SHA256 "${adopt_exact}/.editorconfig" exact_after)
if(NOT exact_before STREQUAL exact_after)
    fail("apply rewrote an exact managed file")
endif()
run_expect_success("${CMAKE_COMMAND}" -DDEVKIT_ROOT=${DEVKIT_ROOT} -DREPOSITORY=${adopt_exact} -P "${DEVKIT_ROOT}/cmake/QivenRepoSync.cmake")
file(SHA256 "${adopt_exact}/.qiven/generated-state.cmake" adopted_state_before)
run_expect_success("${CMAKE_COMMAND}" -DDEVKIT_ROOT=${DEVKIT_ROOT} -DREPOSITORY=${adopt_exact} -P "${DEVKIT_ROOT}/cmake/QivenRepoSync.cmake")
file(SHA256 "${adopt_exact}/.qiven/generated-state.cmake" adopted_state_after)
if(NOT adopted_state_before STREQUAL adopted_state_after)
    fail("second post-adoption sync changed generated state")
endif()
run_adoption(check "${adopt_exact}" readopt_result readopt_output)
assert_adoption_rejected("${readopt_result}" "${readopt_output}" "already managed repository")
string(FIND "${readopt_output}" "sync-repo" readopt_hint)
if(readopt_hint EQUAL -1)
    fail("already-managed rejection did not direct the caller to sync-repo")
endif()

# Missing paths are reported by check and created by apply.
set(adopt_missing "${fixtures}/adopt-missing")
make_adoption_fixture("${adopt_missing}" adopt-fixture)
file(REMOVE "${adopt_missing}/.clang-format" "${adopt_missing}/tools/format.cmd")
file(SHA256 "${adopt_missing}/.editorconfig" missing_exact_before)
commit_adoption_fixture("${adopt_missing}")
run_adoption(check "${adopt_missing}" missing_check_result missing_check_output)
if(NOT missing_check_result EQUAL 0)
    fail("missing-path check failed: ${missing_check_output}")
endif()
foreach(path IN ITEMS .clang-format tools/format.cmd)
    string(FIND "${missing_check_output}" "${path}" missing_position)
    if(missing_position EQUAL -1)
        fail("missing-path plan omitted ${path}")
    endif()
endforeach()
assert_fixture_clean("${adopt_missing}" "missing-path check")
run_adoption(apply "${adopt_missing}" missing_apply_result missing_apply_output)
if(NOT missing_apply_result EQUAL 0)
    fail("missing-path apply failed: ${missing_apply_output}")
endif()
assert_exists("${adopt_missing}/.clang-format")
assert_exists("${adopt_missing}/tools/format.cmd")
file(SHA256 "${adopt_missing}/.editorconfig" missing_exact_after)
if(NOT missing_exact_before STREQUAL missing_exact_after)
    fail("missing-path apply rewrote an exact file")
endif()

# A single conflict rejects check and apply without mutation.
set(adopt_conflict "${fixtures}/adopt-conflict")
make_adoption_fixture("${adopt_conflict}" adopt-fixture)
file(APPEND "${adopt_conflict}/.clang-format" "\n# consumer conflict\n")
commit_adoption_fixture("${adopt_conflict}")
run_adoption(check "${adopt_conflict}" conflict_check_result conflict_check_output)
assert_adoption_rejected("${conflict_check_result}" "${conflict_check_output}" "single conflict check")
assert_fixture_clean("${adopt_conflict}" "single conflict check")
run_adoption(apply "${adopt_conflict}" conflict_apply_result conflict_apply_output)
assert_adoption_rejected("${conflict_apply_result}" "${conflict_apply_output}" "single conflict apply")
assert_fixture_clean("${adopt_conflict}" "single conflict apply")
if(EXISTS "${adopt_conflict}/.qiven")
    fail("conflicting apply created metadata")
endif()

# Multiple conflicts are all reported.
set(adopt_multi "${fixtures}/adopt-multi")
make_adoption_fixture("${adopt_multi}" adopt-fixture)
file(APPEND "${adopt_multi}/.clang-format" "\n# conflict one\n")
file(APPEND "${adopt_multi}/AGENTS.md" "\nconflict two\n")
file(APPEND "${adopt_multi}/tools/format.cmd" "\nrem conflict three\n")
commit_adoption_fixture("${adopt_multi}")
run_adoption(check "${adopt_multi}" multi_result multi_output)
assert_adoption_rejected("${multi_result}" "${multi_output}" "multiple conflicts")
foreach(path IN ITEMS .clang-format AGENTS.md tools/format.cmd)
    string(FIND "${multi_output}" "${path}" multi_position)
    if(multi_position EQUAL -1)
        fail("multiple-conflict plan omitted ${path}")
    endif()
endforeach()
assert_fixture_clean("${adopt_multi}" "multiple conflicts")

# Mixed exact/missing/conflict state remains all-or-nothing.
set(adopt_mixed "${fixtures}/adopt-mixed")
make_adoption_fixture("${adopt_mixed}" adopt-fixture)
file(REMOVE "${adopt_mixed}/.gitattributes")
file(APPEND "${adopt_mixed}/.clang-format" "\n# conflict\n")
commit_adoption_fixture("${adopt_mixed}")
run_adoption(apply "${adopt_mixed}" mixed_result mixed_output)
assert_adoption_rejected("${mixed_result}" "${mixed_output}" "mixed state")
if(EXISTS "${adopt_mixed}/.gitattributes" OR EXISTS "${adopt_mixed}/.qiven")
    fail("mixed-state apply performed a partial mutation")
endif()
assert_fixture_clean("${adopt_mixed}" "mixed state")

# Bootstrap-only divergence and unrelated domain files are preserved.
set(adopt_domain "${fixtures}/adopt-domain")
make_adoption_fixture("${adopt_domain}" adopt-fixture)
foreach(path IN ITEMS README.md CMakeLists.txt .gitignore .github/workflows/ci.yml)
    file(APPEND "${adopt_domain}/${path}" "\nconsumer bootstrap ${path}\n")
endforeach()
file(MAKE_DIRECTORY "${adopt_domain}/include" "${adopt_domain}/src" "${adopt_domain}/tests" "${adopt_domain}/docs/architecture")
foreach(path IN ITEMS include/domain.hpp src/domain.cpp tests/domain.cpp docs/architecture/domain.md)
    file(WRITE "${adopt_domain}/${path}" "consumer domain ${path}\n")
endforeach()
commit_adoption_fixture("${adopt_domain}")
foreach(path IN ITEMS README.md CMakeLists.txt .gitignore .github/workflows/ci.yml include/domain.hpp src/domain.cpp tests/domain.cpp docs/architecture/domain.md)
    string(SHA256 path_key "${path}")
    file(SHA256 "${adopt_domain}/${path}" before_${path_key})
endforeach()
run_adoption(apply "${adopt_domain}" domain_result domain_output)
if(NOT domain_result EQUAL 0)
    fail("bootstrap/domain preservation adoption failed: ${domain_output}")
endif()
foreach(path IN ITEMS README.md CMakeLists.txt .gitignore .github/workflows/ci.yml include/domain.hpp src/domain.cpp tests/domain.cpp docs/architecture/domain.md)
    string(SHA256 path_key "${path}")
    file(SHA256 "${adopt_domain}/${path}" after_${path_key})
    if(NOT before_${path_key} STREQUAL after_${path_key})
        fail("adoption changed consumer file: ${path}")
    endif()
endforeach()

# Dirty repositories: tracked, staged, and untracked changes are each rejected.
foreach(kind IN ITEMS tracked staged untracked)
    set(dirty_repo "${fixtures}/adopt-dirty-${kind}")
    make_adoption_fixture("${dirty_repo}" adopt-fixture)
    commit_adoption_fixture("${dirty_repo}")
    if(kind STREQUAL "untracked")
        file(WRITE "${dirty_repo}/untracked.txt" "dirty\n")
    else()
        file(APPEND "${dirty_repo}/README.md" "\ndirty ${kind}\n")
        if(kind STREQUAL "staged")
            run_expect_success(git -C "${dirty_repo}" add README.md)
        endif()
    endif()
    run_adoption(check "${dirty_repo}" dirty_result dirty_output)
    assert_adoption_rejected("${dirty_result}" "${dirty_output}" "${kind} repository")
endforeach()

# Git eligibility failures.
set(not_git "${fixtures}/adopt-not-git")
make_adoption_fixture("${not_git}" adopt-fixture)
run_adoption(check "${not_git}" not_git_result not_git_output)
assert_adoption_rejected("${not_git_result}" "${not_git_output}" "not a Git repository")

set(subdir_repo "${fixtures}/adopt-subdir")
make_adoption_fixture("${subdir_repo}" adopt-fixture)
file(MAKE_DIRECTORY "${subdir_repo}/child")
commit_adoption_fixture("${subdir_repo}")
if(UNIX)
    set(root_alias "${fixtures}/adopt-root-alias")
    run_expect_success("${CMAKE_COMMAND}" -E create_symlink "${subdir_repo}" "${root_alias}")
    run_adoption(check "${root_alias}" alias_result alias_output)
    if(NOT alias_result EQUAL 0)
        fail("physical Git-root alias was rejected: ${alias_output}")
    endif()
    assert_fixture_clean("${subdir_repo}" "physical Git-root alias check")
endif()
run_adoption(check "${subdir_repo}/child" subdir_result subdir_output)
assert_adoption_rejected("${subdir_result}" "${subdir_output}" "Git subdirectory")

set(no_head "${fixtures}/adopt-no-head")
file(MAKE_DIRECTORY "${no_head}")
run_expect_success(git -C "${no_head}" init -b main)
run_adoption(check "${no_head}" no_head_result no_head_output)
assert_adoption_rejected("${no_head_result}" "${no_head_output}" "repository without HEAD")

set(existing_qiven "${fixtures}/adopt-existing-qiven")
make_adoption_fixture("${existing_qiven}" adopt-fixture)
file(MAKE_DIRECTORY "${existing_qiven}/.qiven")
file(WRITE "${existing_qiven}/.qiven/partial" "partial ownership\n")
commit_adoption_fixture("${existing_qiven}")
run_adoption(check "${existing_qiven}" existing_qiven_result existing_qiven_output)
assert_adoption_rejected("${existing_qiven_result}" "${existing_qiven_output}" "existing .qiven")
assert_fixture_clean("${existing_qiven}" "existing .qiven")

# A directory at a managed-file path is a conflict.
set(non_regular "${fixtures}/adopt-non-regular")
make_adoption_fixture("${non_regular}" adopt-fixture)
file(REMOVE "${non_regular}/.clang-format")
file(MAKE_DIRECTORY "${non_regular}/.clang-format")
file(WRITE "${non_regular}/.clang-format/marker" "collision\n")
commit_adoption_fixture("${non_regular}")
run_adoption(check "${non_regular}" non_regular_result non_regular_output)
assert_adoption_rejected("${non_regular_result}" "${non_regular_output}" "non-regular managed path")

# Foundation-shaped regression: 3 exact paths, Operator policy missing, all other managed paths conflicting.
set(foundation_shape "${fixtures}/adopt-foundation-shape")
make_adoption_fixture("${foundation_shape}" qiven-foundation)
set(foundation_exact .editorconfig .gitattributes tools/delete-all-branches-but-main.cmd)
set(foundation_missing .qiven/operator.json)
foreach(path IN LISTS QIVEN_MANAGED_FILES)
    if(NOT path IN_LIST foundation_exact AND NOT path IN_LIST foundation_missing)
        file(APPEND "${foundation_shape}/${path}" "\nFoundation-shaped managed drift\n")
    endif()
endforeach()
commit_adoption_fixture("${foundation_shape}")
run_adoption(check "${foundation_shape}" foundation_check_result foundation_check_output)
assert_adoption_rejected("${foundation_check_result}" "${foundation_check_output}" "Foundation-shaped check")
foreach(path IN LISTS QIVEN_MANAGED_FILES)
    string(FIND "${foundation_check_output}" "${path}" foundation_position)
    if(foundation_position EQUAL -1)
        fail("Foundation-shaped plan omitted ${path}")
    endif()
endforeach()
assert_fixture_clean("${foundation_shape}" "Foundation-shaped check")
run_adoption(apply "${foundation_shape}" foundation_apply_result foundation_apply_output)
assert_adoption_rejected("${foundation_apply_result}" "${foundation_apply_output}" "Foundation-shaped apply")
assert_fixture_clean("${foundation_shape}" "Foundation-shaped apply")

# Real Windows wrapper, including paths with spaces and exact mode spelling.
if(WIN32 AND DEFINED QIVEN_TOOLCHAIN_ROOT_TEST AND EXISTS "${QIVEN_TOOLCHAIN_ROOT_TEST}/cmake/bin/cmake.exe")
    set(wrapper_repo "${fixtures}/adopt wrapper repo")
    make_adoption_fixture("${wrapper_repo}" wrapper-fixture)
    commit_adoption_fixture("${wrapper_repo}")
    run_expect_success("${CMAKE_COMMAND}" -E env "QIVEN_TOOLCHAIN_ROOT=${QIVEN_TOOLCHAIN_ROOT_TEST}"
        cmd /c "${DEVKIT_ROOT}/tools/adopt-cpp-library.cmd" check "${wrapper_repo}" wrapper-fixture wrapper-fixture
        wrapper-fixture qiven::example qiven::example QIVEN_EXAMPLE_BUILD_TESTS wrapper-fixture)
    run_expect_success("${CMAKE_COMMAND}" -E env "QIVEN_TOOLCHAIN_ROOT=${QIVEN_TOOLCHAIN_ROOT_TEST}"
        cmd /c "${DEVKIT_ROOT}/tools/adopt-cpp-library.cmd" apply "${wrapper_repo}" wrapper-fixture wrapper-fixture
        wrapper-fixture qiven::example qiven::example QIVEN_EXAMPLE_BUILD_TESTS wrapper-fixture)
    execute_process(COMMAND "${CMAKE_COMMAND}" -E env "QIVEN_TOOLCHAIN_ROOT=${QIVEN_TOOLCHAIN_ROOT_TEST}"
        cmd /c "${DEVKIT_ROOT}/tools/adopt-cpp-library.cmd" CHECK "${wrapper_repo}" wrapper-fixture wrapper-fixture
        wrapper-fixture qiven::example qiven::example QIVEN_EXAMPLE_BUILD_TESTS wrapper-fixture RESULT_VARIABLE wrapper_mode_result)
    if(wrapper_mode_result EQUAL 0)
        fail("Windows wrapper accepted non-exact mode spelling")
    endif()
endif()
# Application-profile adoption uses the same managed-surface engine and preserves template identity.
function(run_app_adoption mode repo_path result_variable output_variable)
    execute_process(COMMAND "${CMAKE_COMMAND}"
        -DDEVKIT_ROOT=${DEVKIT_ROOT} -DTEMPLATE_KIND=cpp-app -DMODE=${mode} -DREPOSITORY=${repo_path}
        -DREPOSITORY_NAME=adopt-app -DCMAKE_PROJECT_NAME=adopt-app
        -DCMAKE_TARGET_NAME=adopt-app -DCMAKE_ALIAS=qiven::example-app
        -DCPP_NAMESPACE=qiven::example_app -DTEST_OPTION_NAME=QIVEN_EXAMPLE_APP_BUILD_TESTS
        -DVS_SOLUTION_NAME=adopt-app -P "${DEVKIT_ROOT}/cmake/QivenRepoAdopt.cmake"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    set(${result_variable} "${result}" PARENT_SCOPE)
    set(${output_variable} "${output}\n${error}" PARENT_SCOPE)
endfunction()

set(adopt_app "${fixtures}/adopt-app")
generate_app_repo("${DEVKIT_ROOT}" "${adopt_app}" adopt-app)
file(REMOVE_RECURSE "${adopt_app}/.qiven")
commit_adoption_fixture("${adopt_app}")
run_app_adoption(check "${adopt_app}" app_check_result app_check_output)
if(NOT app_check_result EQUAL 0)
    fail("cpp-app adoption check failed: ${app_check_output}")
endif()
run_app_adoption(apply "${adopt_app}" app_apply_result app_apply_output)
if(NOT app_apply_result EQUAL 0)
    fail("cpp-app adoption apply failed: ${app_apply_output}")
endif()
file(READ "${adopt_app}/.qiven/repo.json" app_adopt_metadata)
string(JSON app_adopt_template GET "${app_adopt_metadata}" template)
if(NOT app_adopt_template STREQUAL "cpp-app")
    fail("cpp-app adoption wrote wrong template identity: ${app_adopt_template}")
endif()

if(WIN32 AND DEFINED QIVEN_TOOLCHAIN_ROOT_TEST AND EXISTS "${QIVEN_TOOLCHAIN_ROOT_TEST}/cmake/bin/cmake.exe")
    set(app_wrapper_repo "${fixtures}/adopt app wrapper")
    generate_app_repo("${DEVKIT_ROOT}" "${app_wrapper_repo}" adopt-app-wrapper)
    file(REMOVE_RECURSE "${app_wrapper_repo}/.qiven")
    commit_adoption_fixture("${app_wrapper_repo}")
    run_expect_success("${CMAKE_COMMAND}" -E env "QIVEN_TOOLCHAIN_ROOT=${QIVEN_TOOLCHAIN_ROOT_TEST}"
        cmd /c "${DEVKIT_ROOT}/tools/adopt-cpp-app.cmd" check "${app_wrapper_repo}" adopt-app-wrapper adopt-app-wrapper
        adopt-app-wrapper qiven::example-app qiven::example_app QIVEN_EXAMPLE_APP_BUILD_TESTS adopt-app-wrapper)
endif()
