cmake_minimum_required(VERSION 3.28)
if(NOT DEFINED DEVKIT_ROOT)
    get_filename_component(DEVKIT_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
endif()

function(fail message_text)
    message(FATAL_ERROR "TEST FAILURE: ${message_text}")
endfunction()
function(assert_exists path)
    if(NOT EXISTS "${path}")
        fail("expected path does not exist: ${path}")
    endif()
endfunction()
function(assert_contains path needle)
    file(READ "${path}" content)
    string(FIND "${content}" "${needle}" position)
    if(position EQUAL -1)
        fail("${path} does not contain: ${needle}")
    endif()
endfunction()
function(assert_not_contains path needle)
    file(READ "${path}" content)
    string(FIND "${content}" "${needle}" position)
    if(NOT position EQUAL -1)
        fail("${path} unexpectedly contains: ${needle}")
    endif()
endfunction()
function(run_expect_success)
    execute_process(COMMAND ${ARGV} RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT result EQUAL 0)
        fail("command failed (${result}): ${ARGV}\n${output}\n${error}")
    endif()
endfunction()
function(generate_repo devkit repo_path repo_name)
    run_expect_success("${CMAKE_COMMAND}"
        -DDEVKIT_ROOT=${devkit} -DDESTINATION=${repo_path}
        -DREPOSITORY_NAME=${repo_name} -DCMAKE_PROJECT_NAME=${repo_name}
        -DCMAKE_TARGET_NAME=${repo_name} -DCMAKE_ALIAS=qiven::example
        -DCPP_NAMESPACE=qiven::example -DTEST_OPTION_NAME=QIVEN_EXAMPLE_BUILD_TESTS
        -DVS_SOLUTION_NAME=${repo_name} -P "${devkit}/cmake/QivenRepoNew.cmake")
endfunction()

string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef nonce)
if(DEFINED ENV{TEMP} AND NOT "$ENV{TEMP}" STREQUAL "" AND IS_DIRECTORY "$ENV{TEMP}")
    set(fixture_parent "$ENV{TEMP}")
elseif(DEFINED ENV{TMPDIR} AND NOT "$ENV{TMPDIR}" STREQUAL "" AND IS_DIRECTORY "$ENV{TMPDIR}")
    set(fixture_parent "$ENV{TMPDIR}")
elseif(DEFINED ENV{TMP} AND NOT "$ENV{TMP}" STREQUAL "" AND IS_DIRECTORY "$ENV{TMP}")
    set(fixture_parent "$ENV{TMP}")
elseif(UNIX AND IS_DIRECTORY "/tmp")
    set(fixture_parent "/tmp")
else()
    fail("no usable temporary directory was found outside the source tree")
endif()
cmake_path(ABSOLUTE_PATH DEVKIT_ROOT NORMALIZE OUTPUT_VARIABLE normalized_devkit_root)
cmake_path(ABSOLUTE_PATH fixture_parent NORMALIZE OUTPUT_VARIABLE normalized_fixture_parent)
set(fixtures "${normalized_fixture_parent}/qiven-devkit-tests-${nonce}")
cmake_path(IS_PREFIX normalized_devkit_root "${fixtures}" fixture_inside_devkit NORMALIZE)
if(fixture_inside_devkit)
    fail("fixture root must be outside DEVKIT_ROOT: ${fixtures}")
endif()
file(MAKE_DIRECTORY "${fixtures}")
set(repo "${fixtures}/qiven-example")

generate_repo("${DEVKIT_ROOT}" "${repo}" qiven-example)

foreach(relative IN ITEMS .clang-format .editorconfig .gitattributes CMakePresets.json AGENTS.md
        tools/resolve-toolchain.cmd tools/format.cmd tools/format-check.cmd tools/gen-vs2022-x64.cmd
        tools/apply-jason-brother.cmd tools/delete-all-branches-but-main.cmd docs/engineering/README.md
        .gitignore README.md CMakeLists.txt .github/workflows/ci.yml .qiven/repo.json .qiven/generated-state.cmake)
    assert_exists("${repo}/${relative}")
endforeach()
assert_contains("${repo}/CMakePresets.json" "QIVEN_EXAMPLE_BUILD_TESTS")
assert_not_contains("${repo}/CMakePresets.json" "QIVEN_BUILD_TESTS")
assert_contains("${repo}/tools/resolve-toolchain.cmd" "..\\..\\qiven-toolchain-win")
assert_contains("${repo}/tools/gen-vs2022-x64.cmd" "qiven-example.sln")

file(GLOB_RECURSE generated_files LIST_DIRECTORIES false "${repo}/*" "${repo}/.*")
foreach(path IN LISTS generated_files)
    assert_not_contains("${path}" "qiven-foundation")
    assert_not_contains("${path}" "${DEVKIT_ROOT}")
endforeach()

file(SHA256 "${repo}/.qiven/generated-state.cmake" state_before)
run_expect_success("${CMAKE_COMMAND}" -DDEVKIT_ROOT=${DEVKIT_ROOT} -DREPOSITORY=${repo} -P "${DEVKIT_ROOT}/cmake/QivenRepoSync.cmake")
file(SHA256 "${repo}/.qiven/generated-state.cmake" state_after)
if(NOT state_before STREQUAL state_after)
    fail("no-op sync changed generated state")
endif()

set(devkit_copy "${fixtures}/devkit-copy")
file(COPY "${DEVKIT_ROOT}/" DESTINATION "${devkit_copy}" PATTERN ".git" EXCLUDE)
file(APPEND "${devkit_copy}/templates/cpp-library/managed/.editorconfig.in" "\n# fixture-template-update\n")
file(READ "${devkit_copy}/templates/cpp-library/managed-files.cmake" manifest)
string(REPLACE "0.1.1" "0.1.2-test" manifest "${manifest}")
file(WRITE "${devkit_copy}/templates/cpp-library/managed-files.cmake" "${manifest}")
run_expect_success("${CMAKE_COMMAND}" -DDEVKIT_ROOT=${devkit_copy} -DREPOSITORY=${repo} -P "${devkit_copy}/cmake/QivenRepoSync.cmake")
assert_contains("${repo}/.editorconfig" "fixture-template-update")
assert_contains("${repo}/.qiven/generated-state.cmake" "0.1.2-test")
file(READ "${repo}/.qiven/repo.json" synced_metadata)
string(JSON synced_repo_version GET "${synced_metadata}" template_version)
include("${repo}/.qiven/generated-state.cmake")
if(NOT synced_repo_version STREQUAL "0.1.2-test" OR NOT QIVEN_TEMPLATE_VERSION STREQUAL synced_repo_version)
    fail("repo metadata and generated state template versions are inconsistent")
endif()

file(APPEND "${repo}/README.md" "\nconsumer readme edit\n")
file(APPEND "${repo}/CMakeLists.txt" "\n# consumer cmake edit\n")
file(APPEND "${repo}/.github/workflows/ci.yml" "\n# consumer ci edit\n")
file(APPEND "${repo}/.clang-format" "\n# consumer managed edit\n")
file(APPEND "${devkit_copy}/templates/cpp-library/managed/.clang-format.in" "\n# devkit managed edit\n")
file(APPEND "${devkit_copy}/templates/cpp-library/managed/.gitattributes.in" "\n# must-not-apply\n")
file(SHA256 "${repo}/.gitattributes" untouched_before)
execute_process(COMMAND "${CMAKE_COMMAND}" -DDEVKIT_ROOT=${devkit_copy} -DREPOSITORY=${repo} -P "${devkit_copy}/cmake/QivenRepoSync.cmake" RESULT_VARIABLE conflict_result)
if(conflict_result EQUAL 0)
    fail("sync accepted a consumer/Devkit conflict")
endif()
file(SHA256 "${repo}/.gitattributes" untouched_after)
if(NOT untouched_before STREQUAL untouched_after)
    fail("conflicting sync was not all-or-nothing")
endif()
assert_contains("${repo}/README.md" "consumer readme edit")
assert_contains("${repo}/CMakeLists.txt" "consumer cmake edit")
assert_contains("${repo}/.github/workflows/ci.yml" "consumer ci edit")

# Managed-set evolution: safe addition, addition collision, removal, removal conflict, and rename.
set(add_devkit "${fixtures}/add-devkit")
file(COPY "${DEVKIT_ROOT}/" DESTINATION "${add_devkit}" PATTERN ".git" EXCLUDE)
file(READ "${add_devkit}/templates/cpp-library/managed-files.cmake" add_manifest)
string(REPLACE "0.1.1" "0.1.2-add" add_manifest "${add_manifest}")
string(REPLACE "    tools/delete-all-branches-but-main.cmd\n)" "    tools/delete-all-branches-but-main.cmd\n    docs/engineering/new-managed.md\n)" add_manifest "${add_manifest}")
file(WRITE "${add_devkit}/templates/cpp-library/managed-files.cmake" "${add_manifest}")
file(WRITE "${add_devkit}/templates/cpp-library/managed/docs/engineering/new-managed.md.in" "# Newly managed\n")

set(add_repo "${fixtures}/add-repo")
generate_repo("${DEVKIT_ROOT}" "${add_repo}" add-repo)
run_expect_success("${CMAKE_COMMAND}" -DDEVKIT_ROOT=${add_devkit} -DREPOSITORY=${add_repo} -P "${add_devkit}/cmake/QivenRepoSync.cmake")
assert_contains("${add_repo}/docs/engineering/new-managed.md" "Newly managed")

set(collision_repo "${fixtures}/collision-repo")
generate_repo("${DEVKIT_ROOT}" "${collision_repo}" collision-repo)
file(WRITE "${collision_repo}/docs/engineering/new-managed.md" "consumer-owned\n")
file(APPEND "${add_devkit}/templates/cpp-library/managed/.editorconfig.in" "\n# collision-atomicity\n")
file(SHA256 "${collision_repo}/.editorconfig" collision_untouched_before)
execute_process(COMMAND "${CMAKE_COMMAND}" -DDEVKIT_ROOT=${add_devkit} -DREPOSITORY=${collision_repo} -P "${add_devkit}/cmake/QivenRepoSync.cmake" RESULT_VARIABLE collision_result)
if(collision_result EQUAL 0)
    fail("new managed path overwrote consumer-owned content")
endif()
file(SHA256 "${collision_repo}/.editorconfig" collision_untouched_after)
if(NOT collision_untouched_before STREQUAL collision_untouched_after)
    fail("addition collision changed another managed file")
endif()
assert_contains("${collision_repo}/docs/engineering/new-managed.md" "consumer-owned")

set(remove_devkit "${fixtures}/remove-devkit")
file(COPY "${DEVKIT_ROOT}/" DESTINATION "${remove_devkit}" PATTERN ".git" EXCLUDE)
file(READ "${remove_devkit}/templates/cpp-library/managed-files.cmake" remove_manifest)
string(REPLACE "0.1.1" "0.1.2-remove" remove_manifest "${remove_manifest}")
string(REPLACE "    .gitattributes\n" "" remove_manifest "${remove_manifest}")
file(WRITE "${remove_devkit}/templates/cpp-library/managed-files.cmake" "${remove_manifest}")

set(remove_repo "${fixtures}/remove-repo")
generate_repo("${DEVKIT_ROOT}" "${remove_repo}" remove-repo)
run_expect_success("${CMAKE_COMMAND}" -DDEVKIT_ROOT=${remove_devkit} -DREPOSITORY=${remove_repo} -P "${remove_devkit}/cmake/QivenRepoSync.cmake")
if(EXISTS "${remove_repo}/.gitattributes")
    fail("untouched removed managed path was preserved")
endif()

set(remove_conflict_repo "${fixtures}/remove-conflict-repo")
generate_repo("${DEVKIT_ROOT}" "${remove_conflict_repo}" remove-conflict-repo)
file(APPEND "${remove_conflict_repo}/.gitattributes" "\nconsumer edit\n")
execute_process(COMMAND "${CMAKE_COMMAND}" -DDEVKIT_ROOT=${remove_devkit} -DREPOSITORY=${remove_conflict_repo} -P "${remove_devkit}/cmake/QivenRepoSync.cmake" RESULT_VARIABLE remove_conflict_result)
if(remove_conflict_result EQUAL 0)
    fail("consumer-modified removed path did not conflict")
endif()
assert_contains("${remove_conflict_repo}/.gitattributes" "consumer edit")

set(old_devkit "${fixtures}/old-devkit")
file(COPY "${DEVKIT_ROOT}/" DESTINATION "${old_devkit}" PATTERN ".git" EXCLUDE)
file(READ "${old_devkit}/templates/cpp-library/managed-files.cmake" old_manifest)
string(REPLACE "    tools/delete-all-branches-but-main.cmd\n)" "    tools/delete-all-branches-but-main.cmd\n    docs/engineering/old-name.md\n)" old_manifest "${old_manifest}")
file(WRITE "${old_devkit}/templates/cpp-library/managed-files.cmake" "${old_manifest}")
file(WRITE "${old_devkit}/templates/cpp-library/managed/docs/engineering/old-name.md.in" "# Renamed content\n")
set(rename_repo "${fixtures}/rename-repo")
generate_repo("${old_devkit}" "${rename_repo}" rename-repo)
set(rename_devkit "${fixtures}/rename-devkit")
file(COPY "${old_devkit}/" DESTINATION "${rename_devkit}")
file(READ "${rename_devkit}/templates/cpp-library/managed-files.cmake" rename_manifest)
string(REPLACE "0.1.1" "0.1.2-rename" rename_manifest "${rename_manifest}")
string(REPLACE "docs/engineering/old-name.md" "docs/engineering/new-name.md" rename_manifest "${rename_manifest}")
file(WRITE "${rename_devkit}/templates/cpp-library/managed-files.cmake" "${rename_manifest}")
file(RENAME "${rename_devkit}/templates/cpp-library/managed/docs/engineering/old-name.md.in" "${rename_devkit}/templates/cpp-library/managed/docs/engineering/new-name.md.in")
run_expect_success("${CMAKE_COMMAND}" -DDEVKIT_ROOT=${rename_devkit} -DREPOSITORY=${rename_repo} -P "${rename_devkit}/cmake/QivenRepoSync.cmake")
if(EXISTS "${rename_repo}/docs/engineering/old-name.md")
    fail("rename did not remove the untouched old managed path")
endif()
assert_contains("${rename_repo}/docs/engineering/new-name.md" "Renamed content")

set(existing "${fixtures}/existing")
file(MAKE_DIRECTORY "${existing}")
file(WRITE "${existing}/keep.txt" "do not overwrite\n")
execute_process(COMMAND "${CMAKE_COMMAND}" -DDEVKIT_ROOT=${DEVKIT_ROOT} -DDESTINATION=${existing}
    -DREPOSITORY_NAME=x -DCMAKE_PROJECT_NAME=x -DCMAKE_TARGET_NAME=x -DCMAKE_ALIAS=qiven::x
    -DCPP_NAMESPACE=qiven::x -DTEST_OPTION_NAME=X_TESTS -DVS_SOLUTION_NAME=x
    -P "${DEVKIT_ROOT}/cmake/QivenRepoNew.cmake" RESULT_VARIABLE protection_result)
if(protection_result EQUAL 0)
    fail("generator overwrote a meaningful destination")
endif()
assert_contains("${existing}/keep.txt" "do not overwrite")

if(WIN32 AND DEFINED QIVEN_TOOLCHAIN_ROOT_TEST AND EXISTS "${QIVEN_TOOLCHAIN_ROOT_TEST}/cmake/bin/cmake.exe")
    set(cmd_repo "${fixtures}/qiven-cmd-example")
    run_expect_success("${CMAKE_COMMAND}" -E env "QIVEN_TOOLCHAIN_ROOT=${QIVEN_TOOLCHAIN_ROOT_TEST}"
        cmd /c "${DEVKIT_ROOT}/tools/new-cpp-library.cmd" "${cmd_repo}" qiven-cmd-example qiven-cmd-example
        qiven-cmd-example qiven::cmd qiven::cmd QIVEN_CMD_BUILD_TESTS qiven-cmd-example)
    run_expect_success("${CMAKE_COMMAND}" -E env "QIVEN_TOOLCHAIN_ROOT=${QIVEN_TOOLCHAIN_ROOT_TEST}"
        cmd /c "${DEVKIT_ROOT}/tools/sync-repo.cmd" "${cmd_repo}")

    # The generated patch tool must pass its patch-exists branch and complete the full workflow.
    # Stub solution generation so this control-flow test does not depend on a host Visual Studio installation.
    file(WRITE "${cmd_repo}/tools/gen-vs2022-x64.cmd" "@echo off\r\nexit /b 0\r\n")
    run_expect_success(git -C "${cmd_repo}" init -b main)
    run_expect_success(git -C "${cmd_repo}" add --all)
    run_expect_success(git -C "${cmd_repo}" -c user.name=QivenFixture -c user.email=fixture@example.invalid commit -m baseline)
    file(APPEND "${cmd_repo}/README.md" "\npatched successfully\n")
    execute_process(COMMAND git -C "${cmd_repo}" diff -- README.md OUTPUT_FILE "${cmd_repo}/jason-brother.patch" RESULT_VARIABLE patch_create_result)
    if(NOT patch_create_result EQUAL 0)
        fail("could not create harmless patch fixture")
    endif()
    run_expect_success(git -C "${cmd_repo}" checkout -- README.md)
    run_expect_success("${CMAKE_COMMAND}" -E env "QIVEN_TOOLCHAIN_ROOT=${QIVEN_TOOLCHAIN_ROOT_TEST}"
        cmd /c "${cmd_repo}/tools/apply-jason-brother.cmd")
    assert_contains("${cmd_repo}/README.md" "patched successfully")
    if(EXISTS "${cmd_repo}/jason-brother.patch")
        fail("successful generated patch tool did not remove the patch")
    endif()
    execute_process(COMMAND "${CMAKE_COMMAND}" -E env "QIVEN_TOOLCHAIN_ROOT=${QIVEN_TOOLCHAIN_ROOT_TEST}"
        cmd /c "${cmd_repo}/tools/apply-jason-brother.cmd" RESULT_VARIABLE missing_patch_result)
    if(missing_patch_result EQUAL 0)
        fail("generated patch tool succeeded without a patch")
    endif()

    # Branch cleanup uses a disposable repository and local bare origin only.
    set(branch_repo "${fixtures}/branch-repo")
    generate_repo("${DEVKIT_ROOT}" "${branch_repo}" branch-repo)
    set(bare_origin "${fixtures}/origin.git")
    run_expect_success(git init --bare "${bare_origin}")
    run_expect_success(git -C "${branch_repo}" init -b main)
    run_expect_success(git -C "${branch_repo}" add --all)
    run_expect_success(git -C "${branch_repo}" -c user.name=QivenFixture -c user.email=fixture@example.invalid commit -m baseline)
    run_expect_success(git -C "${branch_repo}" remote add origin "${bare_origin}")
    run_expect_success(git -C "${branch_repo}" push -u origin main)
    run_expect_success(git --git-dir=${bare_origin} symbolic-ref HEAD refs/heads/main)
    run_expect_success(git -C "${branch_repo}" remote set-head origin -a)
    run_expect_success(git -C "${branch_repo}" branch merged-one)
    run_expect_success(git -C "${branch_repo}" branch nested/merged-two)
    run_expect_success(git -C "${branch_repo}" push origin main:refs/heads/nested/merged-remote)
    run_expect_success("${CMAKE_COMMAND}" -E env "QIVEN_TOOLCHAIN_ROOT=${QIVEN_TOOLCHAIN_ROOT_TEST}"
        cmd /c "${branch_repo}/tools/delete-all-branches-but-main.cmd")
    foreach(ref IN ITEMS refs/heads/merged-one refs/heads/nested/merged-two refs/remotes/origin/nested/merged-remote)
        execute_process(COMMAND git -C "${branch_repo}" show-ref --verify --quiet "${ref}" RESULT_VARIABLE ref_result)
        if(ref_result EQUAL 0)
            fail("merged branch survived cleanup: ${ref}")
        endif()
    endforeach()
    foreach(ref IN ITEMS refs/heads/main refs/remotes/origin/main)
        run_expect_success(git -C "${branch_repo}" show-ref --verify --quiet "${ref}")
    endforeach()
    run_expect_success(git -C "${branch_repo}" symbolic-ref -q refs/remotes/origin/HEAD)
    # Run again with no local or remote candidates to catch fake empty deletion attempts.
    run_expect_success("${CMAKE_COMMAND}" -E env "QIVEN_TOOLCHAIN_ROOT=${QIVEN_TOOLCHAIN_ROOT_TEST}"
        cmd /c "${branch_repo}/tools/delete-all-branches-but-main.cmd")

    run_expect_success(git -C "${branch_repo}" switch -c unmerged/local)
    file(WRITE "${branch_repo}/unmerged.txt" "unmerged\n")
    run_expect_success(git -C "${branch_repo}" add unmerged.txt)
    run_expect_success(git -C "${branch_repo}" -c user.name=QivenFixture -c user.email=fixture@example.invalid commit -m unmerged)
    run_expect_success(git -C "${branch_repo}" push origin HEAD:refs/heads/unmerged/remote)
    run_expect_success(git -C "${branch_repo}" switch main)
    run_expect_success(git -C "${branch_repo}" branch merged-must-survive)
    run_expect_success(git -C "${branch_repo}" push origin main:refs/heads/merged-must-survive)
    execute_process(COMMAND "${CMAKE_COMMAND}" -E env "QIVEN_TOOLCHAIN_ROOT=${QIVEN_TOOLCHAIN_ROOT_TEST}"
        cmd /c "${branch_repo}/tools/delete-all-branches-but-main.cmd" RESULT_VARIABLE blocked_cleanup_result)
    if(blocked_cleanup_result EQUAL 0)
        fail("branch cleanup accepted unmerged candidates")
    endif()
    foreach(ref IN ITEMS refs/heads/main refs/heads/unmerged/local refs/heads/merged-must-survive
            refs/remotes/origin/main refs/remotes/origin/unmerged/remote refs/remotes/origin/merged-must-survive)
        run_expect_success(git -C "${branch_repo}" show-ref --verify --quiet "${ref}")
    endforeach()
    run_expect_success(git -C "${branch_repo}" symbolic-ref -q refs/remotes/origin/HEAD)
endif()

file(REMOVE_RECURSE "${fixtures}")
if(EXISTS "${fixtures}")
    fail("fixture cleanup failed")
endif()
message(STATUS "All qiven-devkit tests passed; disposable fixtures removed")
