include("${CMAKE_CURRENT_LIST_DIR}/QivenRepoCommon.cmake")

foreach(variable IN ITEMS DEVKIT_ROOT MODE REPOSITORY)
    qiven_validate_value(${variable})
endforeach()
if(NOT MODE STREQUAL "check" AND NOT MODE STREQUAL "apply")
    message(FATAL_ERROR "MODE must be exactly check or apply")
endif()

cmake_path(ABSOLUTE_PATH REPOSITORY NORMALIZE OUTPUT_VARIABLE repository)
if(NOT IS_DIRECTORY "${repository}")
    message(FATAL_ERROR "Repository path does not exist or is not a directory: ${repository}")
endif()

find_program(QIVEN_GIT_EXECUTABLE NAMES git REQUIRED)
execute_process(COMMAND "${QIVEN_GIT_EXECUTABLE}" -C "${repository}" rev-parse --show-toplevel
    RESULT_VARIABLE root_result OUTPUT_VARIABLE git_root ERROR_VARIABLE root_error OUTPUT_STRIP_TRAILING_WHITESPACE)
if(NOT root_result EQUAL 0)
    message(FATAL_ERROR "Target is not a Git working tree: ${repository}\n${root_error}")
endif()
file(REAL_PATH "${repository}" repository_real)
file(REAL_PATH "${git_root}" git_root_real)
if(WIN32)
    string(TOLOWER "${repository_real}" repository_compare)
    string(TOLOWER "${git_root_real}" git_root_compare)
else()
    set(repository_compare "${repository_real}")
    set(git_root_compare "${git_root_real}")
endif()
if(NOT repository_compare STREQUAL git_root_compare)
    message(FATAL_ERROR "Target must be the root of its Git working tree: ${repository}")
endif()

execute_process(COMMAND "${QIVEN_GIT_EXECUTABLE}" -C "${repository}" rev-parse --verify HEAD
    RESULT_VARIABLE head_result OUTPUT_QUIET ERROR_VARIABLE head_error)
if(NOT head_result EQUAL 0)
    message(FATAL_ERROR "Target Git repository has no HEAD commit: ${repository}\n${head_error}")
endif()
execute_process(COMMAND "${QIVEN_GIT_EXECUTABLE}" --no-optional-locks -C "${repository}" status --porcelain=v1 --untracked-files=all
    RESULT_VARIABLE status_result OUTPUT_VARIABLE porcelain ERROR_VARIABLE status_error)
if(NOT status_result EQUAL 0)
    message(FATAL_ERROR "Could not inspect target Git status: ${status_error}")
endif()
if(NOT porcelain STREQUAL "")
    message(FATAL_ERROR "Target Git repository is not clean; Operator materialization made no changes")
endif()

set(component "${DEVKIT_ROOT}/components/operator")
include("${component}/managed-files.cmake")
if(NOT EXISTS "${repository}/.qiven/operator.json")
    message(FATAL_ERROR "Repository must own .qiven/operator.json before Operator runtime materialization")
endif()

string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef nonce)
set(stage "${repository}.qiven-operator-${nonce}")
cmake_path(IS_PREFIX repository "${stage}" stage_inside_repository NORMALIZE)
if(stage_inside_repository)
    message(FATAL_ERROR "Could not place Operator staging outside the target repository: ${repository}")
endif()
if(EXISTS "${stage}" OR IS_SYMLINK "${stage}")
    message(FATAL_ERROR "Temporary path already exists: ${stage}")
endif()
file(MAKE_DIRECTORY "${stage}")

foreach(relative IN LISTS QIVEN_OPERATOR_MANAGED_FILES)
    qiven_validate_managed_path("${relative}")
    qiven_render("${component}/managed/${relative}.in" "${stage}/${relative}")
endforeach()

set(exact_paths "")
set(missing_paths "")
set(conflict_paths "")
foreach(relative IN LISTS QIVEN_OPERATOR_MANAGED_FILES)
    set(parent_collision FALSE)
    get_filename_component(parent_relative "${relative}" DIRECTORY)
    while(NOT parent_relative STREQUAL "")
        if(IS_SYMLINK "${repository}/${parent_relative}" OR
                (EXISTS "${repository}/${parent_relative}" AND NOT IS_DIRECTORY "${repository}/${parent_relative}"))
            set(parent_collision TRUE)
            break()
        endif()
        get_filename_component(parent_relative "${parent_relative}" DIRECTORY)
    endwhile()
    if(parent_collision OR IS_DIRECTORY "${repository}/${relative}" OR IS_SYMLINK "${repository}/${relative}")
        list(APPEND conflict_paths "${relative}")
    elseif(NOT EXISTS "${repository}/${relative}")
        list(APPEND missing_paths "${relative}")
    else()
        qiven_hash("${repository}/${relative}" current_hash)
        qiven_hash("${stage}/${relative}" desired_hash)
        if(current_hash STREQUAL desired_hash)
            list(APPEND exact_paths "${relative}")
        else()
            list(APPEND conflict_paths "${relative}")
        endif()
    endif()
endforeach()

function(qiven_print_operator_category label paths_variable)
    message(STATUS "${label}:")
    foreach(relative IN LISTS ${paths_variable})
        message(STATUS "  ${relative}")
    endforeach()
endfunction()

message(STATUS "Qiven Operator materialization plan ${QIVEN_OPERATOR_COMPONENT_VERSION}")
qiven_print_operator_category("EXACT" exact_paths)
qiven_print_operator_category("MISSING" missing_paths)
qiven_print_operator_category("CONFLICT" conflict_paths)

if(conflict_paths)
    file(REMOVE_RECURSE "${stage}")
    list(JOIN conflict_paths ", " conflict_text)
    message(FATAL_ERROR "Operator runtime conflict; no repository files changed: ${conflict_text}")
endif()

if(MODE STREQUAL "check")
    file(REMOVE_RECURSE "${stage}")
    message(STATUS "Operator materialization check passed; target repository was not changed")
    return()
endif()

foreach(relative IN LISTS missing_paths)
    get_filename_component(parent "${repository}/${relative}" DIRECTORY)
    file(MAKE_DIRECTORY "${parent}")
    execute_process(COMMAND "${CMAKE_COMMAND}" -E copy "${stage}/${relative}" "${repository}/${relative}"
        COMMAND_ERROR_IS_FATAL ANY)
endforeach()
file(REMOVE_RECURSE "${stage}")
message(STATUS "Materialized Qiven Operator runtime ${QIVEN_OPERATOR_COMPONENT_VERSION} into ${repository}")
