include("${CMAKE_CURRENT_LIST_DIR}/QivenRepoCommon.cmake")
qiven_require(DEVKIT_ROOT)
qiven_require(REPOSITORY)
cmake_path(ABSOLUTE_PATH REPOSITORY NORMALIZE OUTPUT_VARIABLE repository)
set(metadata "${repository}/.qiven/repo.json")
set(state_file "${repository}/.qiven/generated-state.cmake")
if(NOT EXISTS "${metadata}" OR NOT EXISTS "${state_file}")
    message(FATAL_ERROR "Repository lacks qiven-devkit metadata: ${repository}")
endif()

file(READ "${metadata}" json)
function(read_metadata field variable)
    string(JSON value ERROR_VARIABLE json_error GET "${json}" "${field}")
    if(json_error)
        message(FATAL_ERROR "Invalid metadata field ${field}: ${json_error}")
    endif()
    set(${variable} "${value}" PARENT_SCOPE)
endfunction()
read_metadata(schema_version REPO_SCHEMA_VERSION)
if(NOT REPO_SCHEMA_VERSION EQUAL 1)
    message(FATAL_ERROR "Unsupported repository metadata schema: ${REPO_SCHEMA_VERSION}")
endif()
read_metadata(template TEMPLATE_KIND)
read_metadata(repository_name REPOSITORY_NAME)
read_metadata(cmake_project_name CMAKE_PROJECT_NAME)
read_metadata(cmake_target_name CMAKE_TARGET_NAME)
read_metadata(cmake_alias CMAKE_ALIAS)
read_metadata(cpp_namespace CPP_NAMESPACE)
read_metadata(test_option_name TEST_OPTION_NAME)
read_metadata(vs_solution_name VS_SOLUTION_NAME)
qiven_validate_template_kind("${TEMPLATE_KIND}")
set(template "${DEVKIT_ROOT}/templates/${TEMPLATE_KIND}")
if(NOT EXISTS "${template}/managed-files.cmake" OR NOT EXISTS "${template}/repo.json.in")
    message(FATAL_ERROR "Unsupported template: ${TEMPLATE_KIND}")
endif()
include("${template}/managed-files.cmake")
set(new_template_version "${QIVEN_TEMPLATE_VERSION}")
set(new_managed_files ${QIVEN_MANAGED_FILES})
foreach(relative IN LISTS new_managed_files)
    qiven_validate_managed_path("${relative}")
endforeach()

include("${state_file}")
if(NOT DEFINED QIVEN_STATE_SCHEMA OR NOT QIVEN_STATE_SCHEMA EQUAL 2)
    message(FATAL_ERROR "Unsupported generated-state schema; expected schema 2")
endif()
if(NOT DEFINED QIVEN_MANAGED_PATHS)
    message(FATAL_ERROR "Generated state does not record the previous managed path set")
endif()
set(old_managed_files ${QIVEN_MANAGED_PATHS})
foreach(relative IN LISTS old_managed_files)
    qiven_validate_managed_path("${relative}")
    qiven_state_key("${relative}" key)
    if(NOT DEFINED ${key})
        message(FATAL_ERROR "Generated state lacks a hash for previous managed path: ${relative}")
    endif()
endforeach()

string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef nonce)
set(stage "${repository}/.qiven/sync-${nonce}")
file(MAKE_DIRECTORY "${stage}")
foreach(relative IN LISTS new_managed_files)
    qiven_render_managed("${relative}" "${stage}/${relative}")
endforeach()
set(QIVEN_TEMPLATE_VERSION "${new_template_version}")
qiven_render("${template}/repo.json.in" "${stage}/repo.json")

set(all_paths ${old_managed_files} ${new_managed_files})
list(REMOVE_DUPLICATES all_paths)
set(copy_plan "")
set(delete_plan "")
set(conflicts "")
foreach(relative IN LISTS all_paths)
    set(in_old FALSE)
    set(in_new FALSE)
    if(relative IN_LIST old_managed_files)
        set(in_old TRUE)
    endif()
    if(relative IN_LIST new_managed_files)
        set(in_new TRUE)
    endif()
    qiven_hash("${repository}/${relative}" current_hash)
    if(in_old)
        qiven_state_key("${relative}" old_key)
        set(old_hash "${${old_key}}")
    endif()
    if(in_new)
        qiven_hash("${stage}/${relative}" new_hash)
    endif()

    if(in_old AND in_new)
        if(current_hash STREQUAL old_hash)
            if(NOT current_hash STREQUAL new_hash)
                list(APPEND copy_plan "${relative}")
            endif()
        elseif(NOT current_hash STREQUAL new_hash)
            list(APPEND conflicts "${relative}")
        endif()
    elseif(in_new)
        if(current_hash STREQUAL "MISSING")
            list(APPEND copy_plan "${relative}")
        elseif(NOT current_hash STREQUAL new_hash)
            list(APPEND conflicts "${relative}")
        endif()
    else()
        if(current_hash STREQUAL old_hash)
            list(APPEND delete_plan "${relative}")
        elseif(NOT current_hash STREQUAL "MISSING")
            list(APPEND conflicts "${relative}")
        endif()
    endif()
endforeach()

if(conflicts)
    file(REMOVE_RECURSE "${stage}")
    list(JOIN conflicts ", " conflict_text)
    message(FATAL_ERROR "Managed-file conflict; no files changed: ${conflict_text}")
endif()

foreach(relative IN LISTS copy_plan)
    get_filename_component(parent "${repository}/${relative}" DIRECTORY)
    file(MAKE_DIRECTORY "${parent}")
    execute_process(COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${stage}/${relative}" "${repository}/${relative}" COMMAND_ERROR_IS_FATAL ANY)
endforeach()
foreach(relative IN LISTS delete_plan)
    file(REMOVE "${repository}/${relative}")
endforeach()
execute_process(COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${stage}/repo.json" "${metadata}" COMMAND_ERROR_IS_FATAL ANY)
set(QIVEN_MANAGED_FILES ${new_managed_files})
qiven_write_state("${repository}" "${stage}")
file(REMOVE_RECURSE "${stage}")
message(STATUS "Synchronized managed files in ${repository}")
