include("${CMAKE_CURRENT_LIST_DIR}/QivenRepoCommon.cmake")
qiven_require(DEVKIT_ROOT)
qiven_require(REPOSITORY)
cmake_path(ABSOLUTE_PATH REPOSITORY NORMALIZE OUTPUT_VARIABLE repository)
set(metadata "${repository}/.qiven/repo.json")
set(state_file "${repository}/.qiven/generated-state.cmake")
if(NOT EXISTS "${metadata}" OR NOT EXISTS "${state_file}")
    message(FATAL_ERROR "Repository lacks qiven-devkit metadata: ${repository}\n"
        "  rule: qivenrepo/sync/not-managed (sync rolls OWNED managed files; the "
        "ownership state files are missing)\n"
        "  evidence: expected ${metadata} and ${state_file}\n"
        "  NEXT: FIX - adopt first: adopt_cpp_library.py apply REPOSITORY ... ; "
        "sync only updates already-managed repositories")
endif()

file(READ "${metadata}" json)
function(read_metadata field variable)
    string(JSON value ERROR_VARIABLE json_error GET "${json}" "${field}")
    if(json_error)
        message(FATAL_ERROR "Invalid metadata field ${field}: ${json_error}\n"
            "  rule: qivenrepo/sync/invalid-metadata (${metadata} does not parse "
            "for the required field)\n"
            "  NEXT: RECONCILE - the ownership metadata is damaged; re-create it "
            "by re-running adoption (or repair ${metadata} by hand against "
            "templates/*/repo.json.in), then re-run sync")
    endif()
    set(${variable} "${value}" PARENT_SCOPE)
endfunction()
read_metadata(schema_version REPO_SCHEMA_VERSION)
if(NOT REPO_SCHEMA_VERSION EQUAL 1)
    message(FATAL_ERROR "Unsupported repository metadata schema: ${REPO_SCHEMA_VERSION}\n"
        "  rule: qivenrepo/sync/unsupported-metadata-schema (this devkit reads "
        "schema 1 only)\n"
        "  NEXT: RECONCILE - the metadata was written by a different devkit "
        "generation; sync this repository from that devkit checkout, or re-adopt "
        "from the current one")
endif()
read_metadata(template TEMPLATE_KIND)
read_metadata(repository_name REPOSITORY_NAME)
read_metadata(cmake_project_name CMAKE_PROJECT_NAME)
read_metadata(cmake_target_name CMAKE_TARGET_NAME)
read_metadata(cmake_alias CMAKE_ALIAS)
read_metadata(cpp_namespace CPP_NAMESPACE)
read_metadata(test_option_name TEST_OPTION_NAME)
read_metadata(vs_solution_name VS_SOLUTION_NAME)
if(NOT TEMPLATE_KIND MATCHES "^(cpp-library|cpp-app)$")
    message(FATAL_ERROR "Unsupported template: ${TEMPLATE_KIND}\n"
        "  rule: qivenrepo/sync/unsupported-template (no templates/${TEMPLATE_KIND}/ "
        "under this devkit)\n"
        "  NEXT: RECONCILE - the repository was generated by a template family "
        "this devkit does not carry; sync from a devkit that has it")
endif()

set(TEMPLATE "${TEMPLATE_KIND}")
set(template "${DEVKIT_ROOT}/templates/${TEMPLATE_KIND}")
include("${template}/managed-files.cmake")
if(NOT DEFINED QIVEN_MANAGED_SOURCE_DIR)
    set(QIVEN_MANAGED_SOURCE_DIR "${template}")
endif()
if(NOT DEFINED QIVEN_SEED_ONLY_FILES)
    set(QIVEN_SEED_ONLY_FILES "")
endif()
set(new_template_version "${QIVEN_TEMPLATE_VERSION}")
set(new_managed_files ${QIVEN_MANAGED_FILES})
foreach(relative IN LISTS new_managed_files)
    qiven_validate_managed_path("${relative}")
endforeach()

include("${state_file}")
if(NOT DEFINED QIVEN_STATE_SCHEMA OR NOT QIVEN_STATE_SCHEMA EQUAL 2)
    message(FATAL_ERROR "Unsupported generated-state schema; expected schema 2\n"
        "  rule: qivenrepo/sync/unsupported-state-schema (this devkit reads state "
        "schema 2 only)\n"
        "  NEXT: RECONCILE - the generated state was written by a different devkit "
        "generation; re-adopt from the current devkit or sync from the one that "
        "wrote it")
endif()
if(NOT DEFINED QIVEN_MANAGED_PATHS)
    message(FATAL_ERROR "Generated state does not record the previous managed path set\n"
        "  rule: qivenrepo/sync/state-missing-path-set (state schema 2 must record "
        "QIVEN_MANAGED_PATHS so removals are provable)\n"
        "  evidence: ${state_file} parsed but carries no path set\n"
        "  NEXT: RECONCILE - the state file is damaged; re-adopt from the current "
        "devkit to regenerate it")
endif()
set(old_managed_files ${QIVEN_MANAGED_PATHS})
foreach(relative IN LISTS old_managed_files)
    qiven_validate_managed_path("${relative}")
    qiven_state_key("${relative}" key)
    if(NOT DEFINED ${key})
        message(FATAL_ERROR "Generated state lacks a hash for previous managed path: ${relative}\n"
            "  rule: qivenrepo/sync/state-missing-hash (every recorded path must "
            "carry its generated hash)\n"
            "  evidence: no hash for ${relative} in ${state_file}\n"
            "  NEXT: RECONCILE - the state file is damaged; re-adopt from the "
            "current devkit to regenerate it")
    endif()
endforeach()

string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef nonce)
set(stage "${repository}/.qiven/sync-${nonce}")
file(MAKE_DIRECTORY "${stage}")
foreach(relative IN LISTS new_managed_files)
    qiven_render("${QIVEN_MANAGED_SOURCE_DIR}/managed/${relative}.in" "${stage}/${relative}")
endforeach()
set(QIVEN_TEMPLATE_VERSION "${new_template_version}")
qiven_render("${template}/repo.json.in" "${stage}/repo.json")

set(all_paths ${old_managed_files} ${new_managed_files})
list(REMOVE_DUPLICATES all_paths)
set(copy_plan "")
set(delete_plan "")
set(conflicts "")
foreach(relative IN LISTS all_paths)
    set(in_old FALSE)
    set(in_new FALSE)
    if(relative IN_LIST old_managed_files)
        set(in_old TRUE)
    endif()
    if(relative IN_LIST new_managed_files)
        set(in_new TRUE)
    endif()
    qiven_hash("${repository}/${relative}" current_hash)
    if(in_old)
        qiven_state_key("${relative}" old_key)
        set(old_hash "${${old_key}}")
    endif()
    if(in_new)
        qiven_hash("${stage}/${relative}" new_hash)
    endif()

    if(in_old AND NOT in_new AND relative IN_LIST QIVEN_SEED_ONLY_FILES)
        # Seed-only handoff (v61 owner decision): the path leaves the
        # managed set into repository ownership. Sync keeps the file
        # untouched, whatever its bytes, and drops it from the recorded
        # state; it is never deleted and never conflict-checked.
        continue()
    endif()
    if(in_old AND in_new)
        if(current_hash STREQUAL old_hash)
            if(NOT current_hash STREQUAL new_hash)
                list(APPEND copy_plan "${relative}")
            endif()
        elseif(NOT current_hash STREQUAL new_hash)
            list(APPEND conflicts "${relative}")
        endif()
    elseif(in_new)
        if(current_hash STREQUAL "MISSING")
            list(APPEND copy_plan "${relative}")
        elseif(NOT current_hash STREQUAL new_hash)
            list(APPEND conflicts "${relative}")
        endif()
    else()
        if(current_hash STREQUAL old_hash)
            list(APPEND delete_plan "${relative}")
        elseif(NOT current_hash STREQUAL "MISSING")
            list(APPEND conflicts "${relative}")
        endif()
    endif()
endforeach()

if(conflicts)
    file(REMOVE_RECURSE "${stage}")
    list(JOIN conflicts ", " conflict_text)
    message(FATAL_ERROR "Managed-file conflict; no files changed: ${conflict_text}\n"
        "  rule: qivenrepo/sync/conflict (a consumer-modified managed file: its "
        "bytes match neither the last-synchronized state nor the new template "
        "render; the roll is all-or-nothing, so nothing was changed)\n"
        "  evidence: conflicting path(s): ${conflict_text}\n"
        "  NEXT: FIX - for each listed path: port your local change into the "
        "devkit template, or restore the generated bytes (git checkout -- <path>); "
        "commit, then re-run sync")
endif()

foreach(relative IN LISTS copy_plan)
    get_filename_component(parent "${repository}/${relative}" DIRECTORY)
    file(MAKE_DIRECTORY "${parent}")
    execute_process(COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${stage}/${relative}" "${repository}/${relative}" COMMAND_ERROR_IS_FATAL ANY)
endforeach()
foreach(relative IN LISTS delete_plan)
    file(REMOVE "${repository}/${relative}")
endforeach()
execute_process(COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${stage}/repo.json" "${metadata}" COMMAND_ERROR_IS_FATAL ANY)
set(QIVEN_MANAGED_FILES ${new_managed_files})
qiven_write_state("${repository}" "${stage}")
file(REMOVE_RECURSE "${stage}")
message(STATUS "Synchronized managed files in ${repository}")
