include("${CMAKE_CURRENT_LIST_DIR}/QivenRepoCommon.cmake")
if(NOT DEFINED TEMPLATE_KIND OR "${TEMPLATE_KIND}" STREQUAL "")
    set(TEMPLATE_KIND "cpp-library")
endif()
foreach(variable IN ITEMS DEVKIT_ROOT DESTINATION REPOSITORY_NAME CMAKE_PROJECT_NAME CMAKE_TARGET_NAME CMAKE_ALIAS CPP_NAMESPACE TEST_OPTION_NAME VS_SOLUTION_NAME TEMPLATE_KIND)
    qiven_validate_value(${variable})
endforeach()
qiven_validate_template_kind("${TEMPLATE_KIND}")

cmake_path(ABSOLUTE_PATH DESTINATION NORMALIZE OUTPUT_VARIABLE destination)
if(EXISTS "${destination}")
    file(GLOB existing LIST_DIRECTORIES true "${destination}/*" "${destination}/.*")
    list(FILTER existing EXCLUDE REGEX "/\.\.?$")
    if(existing)
        message(FATAL_ERROR "Destination contains existing content: ${destination}")
    endif()
endif()

set(template "${DEVKIT_ROOT}/templates/${TEMPLATE_KIND}")
if(NOT EXISTS "${template}/managed-files.cmake" OR NOT EXISTS "${template}/repo.json.in")
    message(FATAL_ERROR "Unsupported repository template: ${TEMPLATE_KIND}")
endif()
include("${template}/managed-files.cmake")
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef nonce)
set(stage "${destination}.qiven-new-${nonce}")
if(EXISTS "${stage}")
    message(FATAL_ERROR "Temporary path already exists: ${stage}")
endif()
file(MAKE_DIRECTORY "${stage}")

foreach(relative IN LISTS QIVEN_MANAGED_FILES)
    qiven_validate_managed_path("${relative}")
    qiven_render_managed("${relative}" "${stage}/${relative}")
endforeach()
foreach(relative IN LISTS QIVEN_BOOTSTRAP_FILES)
    qiven_validate_managed_path("${relative}")
    qiven_render("${template}/bootstrap-only/${relative}.in" "${stage}/${relative}")
endforeach()

file(MAKE_DIRECTORY "${stage}/.qiven")
qiven_render("${template}/repo.json.in" "${stage}/.qiven/repo.json")
qiven_write_state("${stage}" "${stage}")

if(EXISTS "${destination}")
    file(REMOVE_RECURSE "${destination}")
endif()
file(RENAME "${stage}" "${destination}" RESULT rename_result)
if(rename_result)
    file(REMOVE_RECURSE "${stage}")
    message(FATAL_ERROR "Could not publish generated repository: ${rename_result}")
endif()
message(STATUS "Generated ${REPOSITORY_NAME} at ${destination}")
