include("${CMAKE_CURRENT_LIST_DIR}/QivenRepoCommon.cmake")
qiven_require(DEVKIT_ROOT)
qiven_require(REPOSITORY)
cmake_path(ABSOLUTE_PATH REPOSITORY NORMALIZE OUTPUT_VARIABLE repository)
set(metadata "${repository}/.qiven/repo.json")
set(state_file "${repository}/.qiven/generated-state.cmake")
if(NOT EXISTS "${metadata}" OR NOT EXISTS "${state_file}")
    message(FATAL_ERROR "Repository lacks qiven-devkit metadata: ${repository}")
endif()
file(READ "${metadata}" json)
function(read_metadata field variable)
    string(JSON value ERROR_VARIABLE json_error GET "${json}" "${field}")
    if(json_error)
        message(FATAL_ERROR "Invalid metadata field ${field}: ${json_error}")
    endif()
    set(${variable} "${value}")
    set(${variable} "${value}" PARENT_SCOPE)
endfunction()
read_metadata(template TEMPLATE_KIND)
read_metadata(repository_name REPOSITORY_NAME)
read_metadata(cmake_project_name CMAKE_PROJECT_NAME)
read_metadata(cmake_target_name CMAKE_TARGET_NAME)
read_metadata(cmake_alias CMAKE_ALIAS)
read_metadata(cpp_namespace CPP_NAMESPACE)
read_metadata(test_option_name TEST_OPTION_NAME)
read_metadata(vs_solution_name VS_SOLUTION_NAME)
if(NOT TEMPLATE_KIND STREQUAL "cpp-library")
    message(FATAL_ERROR "Unsupported template: ${TEMPLATE_KIND}")
endif()
set(template "${DEVKIT_ROOT}/templates/${TEMPLATE_KIND}")
include("${template}/managed-files.cmake")
set(new_template_version "${QIVEN_TEMPLATE_VERSION}")
include("${state_file}")
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef nonce)
set(stage "${repository}/.qiven/sync-${nonce}")
file(MAKE_DIRECTORY "${stage}")
set(conflicts "")
foreach(relative IN LISTS QIVEN_MANAGED_FILES)
    qiven_render("${template}/managed/${relative}.in" "${stage}/${relative}")
    qiven_hash("${repository}/${relative}" current_hash)
    qiven_hash("${stage}/${relative}" new_hash)
    qiven_state_key("${relative}" key)
    if(NOT DEFINED ${key})
        list(APPEND conflicts "${relative} (no prior hash)")
    elseif(NOT current_hash STREQUAL "${${key}}" AND NOT current_hash STREQUAL new_hash)
        list(APPEND conflicts "${relative}")
    endif()
endforeach()
if(conflicts)
    file(REMOVE_RECURSE "${stage}")
    list(JOIN conflicts ", " conflict_text)
    message(FATAL_ERROR "Managed-file conflict; no files changed: ${conflict_text}")
endif()
foreach(relative IN LISTS QIVEN_MANAGED_FILES)
    execute_process(COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${stage}/${relative}" "${repository}/${relative}" COMMAND_ERROR_IS_FATAL ANY)
endforeach()
set(QIVEN_TEMPLATE_VERSION "${new_template_version}")
qiven_write_state("${repository}" "${stage}")
file(REMOVE_RECURSE "${stage}")
message(STATUS "Synchronized managed files in ${repository}")
